spring.application.name=E-Commers_BE

server.servlet.contextPath=/api

spring.data.mongodb.uri=mongodb://localhost:27017/e_commerce_be
spring.data.mongodb.repositories.enable=true
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.isSslEnable=false
spring.data.mongodb.maximumConnectionCount=10
spring.data.mongodb.minimumConnectionCount=2